[package]
name = "airtable"
version = "0.1.0"
authors = ["Simon Eskildsen <sirup@sirupsen.com>"]

[dependencies]
reqwest = "0.9.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
failure = "0.1"

[dev-dependencies]
mockito = "0.13"
dotenv = "0.13"
